version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/docker/mock-server"
    schedule:
      interval: "monthly"
    reviewers:
      - DeployGate/gradle-plugin-reviewer
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker/mock-server"
    schedule:
      interval: "monthly"
    reviewers:
      - DeployGate/gradle-plugin-reviewer
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - DeployGate/gradle-plugin-reviewer
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - DeployGate/gradle-plugin-reviewer
