version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - DeployGate/gradle-plugin-reviewer
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - DeployGate/gradle-plugin-reviewer
    open-pull-requests-limit: 3
