language: java
branches:
  only: auto_release
env:
  global:
  - secure: RrOxRkXn7IHW3kz1qg4X9XC99qB7Kt6tEFOlKSIpkZjFjst+TchaYzupt6ZplQ8Syj1tEhh6OibP3c0SIdtF4ztTViirgzRtbXXNbNICoYuDPxFFIWIN5eq6HgNnRf7aPy/oDi0sVtLmPaKG06MgviiSgEpnF6MhBgVKA6/CAfI=
  - secure: Lt10jFXW5FQxmmX6PQlBu6yTaTadurq6eFqkDFoBiPjauzRWTiy75e079+db7OMkdJsJrYXwbxLHP8XFj0uUfNuKEVS+uzIAs1iXRc9lsFsTGytXiSSQMXhDljNacZVNYoe70UtxIwgU2LreqXxJxQr4DRAuuv1qc2PqPYf9CB4=
  - secure: b0HU1LBDDUyMORC9w9Y5wEWbSrD0eMpKxQVIC8xvMJRT4tvEZSBePwzwoQqj2G5fDB7XMwhiQhlgf88k4jVMkGwYwn/iT97cuCmj40f9DSobR1wZiP9OmxNfbJ2tNvpK4GsBi+0hJQarDBJhe+fWuJJnmVIsEMr8x+CdhFr6+Nk=
jdk:
- openjdk7
before_install:
- openssl aes-256-cbc -K $encrypted_3d2a2d8844ff_key -iv $encrypted_3d2a2d8844ff_iv
  -in secret.key.enc -out ./secret.key -d
- openssl aes-256-cbc -K $encrypted_3d2a2d8844ff_key -iv $encrypted_3d2a2d8844ff_iv
  -in pub.key.enc -out ./pub.key -d
- gpg --import pub.key
- gpg --import --allow-secret-key-import secret.key
script:
- "./gradlew build test"
- "./gradlew clean build uploadArchives -Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg
  -PsonatypeUsername=henteko -PsonatypeFullname=deploygate -Psigning.keyId=$SIGNING_KEY_ID
  -Psigning.password=$SIGNING_PASSWORD -PsonatypePassword=$SONATYPE_PASSWORD"
notifications:
  slack:
    secure: AKYACFZgCynbYDQnYy84nluHckTKA/p7Q5IlN4MzPwz7Hz9aDoa9upOR+6puJgPVerlLIiQYGztyzbu5O5NowqRdssVqWT+tIuAvg8xY6jb0wgLPfyCmMpJz728aunbwBSBqgxs7hKtnHVFhaIYnEvnYL31DiDGO3tarKVg23OU=
