language: android
sudo: false
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.android"
  - ".gradle"
android:
  components:
  - platform-tools
  - android-26
  - android-28
  - build-tools-26.0.2
  - build-tools-27.0.3
  - build-tools-28.0.2
  - build-tools-28.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  - tools
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
env:
  matrix:
    - GRADLE_TASK_NAME=install
    - GRADLE_TASK_NAME=test
    - GRADLE_TASK_NAME=acceptanceTest
script:
- echo "sdk.dir=$ANDROID_HOME" > src/test/resources/project/local.properties
- echo "ndk.dir=$ANDROID_HOME/ndk-bundle" >> src/test/resources/project/local.properties
- "./gradlew $GRADLE_TASK_NAME"
deploy:
  provider: script
  script: ./release.sh
  on:
    tags: true
    repo: DeployGate/gradle-deploygate-plugin
after_deploy:
- 'curl -X POST --data-urlencode "payload={\"text\": \"Released a gradle-deploygate-plugin in Bintray! Please check <https://bintray.com/deploygate/maven|Bintray>\"}" $SLACK_URL'
