name: 'Set up Java'
inputs:
  java-version:
    default: '8'
    required: false
  android-components:
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: 11 # for sdkmanager
        distribution: 'temurin'
        cache: 'gradle'
    - uses: android-actions/setup-android@v2
    - run: sdkmanager "build-tools;29.0.2" "build-tools;30.0.0" "build-tools;30.0.2" "platforms;android-29" "platform-tools" ${{ inputs.android-components }}
      shell: bash
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'gradle'
