name: Build and run tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      app:
        image: ghcr.io/deploygate/gradle-plugin-mock-server
        ports:
          - 3000/tcp
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-java
        with:
          java-version: '8'
      - run: ./gradlew publishToMavenLocal test
        env:
          TEST_SERVER_URL: http://localhost:${{ job.services.app.ports[3000] }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: build/test-results/tests/test

  acceptance-test:
    runs-on: ubuntu-latest
    services:
      app:
        image: ghcr.io/deploygate/gradle-plugin-mock-server
        credentials:
          username: ${{ github.actor }}
          password: ${{ github.token }}
        ports:
          - 3000/tcp
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-java
        with:
          java-version: '8'
      - run: ./gradlew testUnrollAcceptanceTest
        env:
          TEST_SERVER_URL: http://localhost:${{ job.services.app.ports[3000] }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/testUnrollAcceptanceTest
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: build/test-results/tests/testUnrollAcceptanceTest

  acceptance-test-runtime-env:
    runs-on: ubuntu-latest
    services:
      app:
        image: ghcr.io/deploygate/gradle-plugin-mock-server
        credentials:
          username: ${{ github.actor }}
          password: ${{ github.token }}
        ports:
          - 3000/tcp
    strategy:
      fail-fast: false
      matrix:
        agp_version:
          - '3.5.1'
          - '3.6.3'
          - '4.0.0'
          - '4.1.0'
          - '7.0.0'
          - '7.1.0'
          - '7.2.0'
          - '7.3.0'
          - '7.4.0-rc02'
        include:
          - agp_version: '3.5.1'
            gradle_version: '5.4.1'
            java_version: '8'
          - agp_version: '3.6.3'
            gradle_version: '5.6.4'
            java_version: '8'
          - agp_version: '4.0.0'
            gradle_version: '6.1.1'
            java_version: '8'
          - agp_version: '4.1.0'
            gradle_version: '6.5'
            java_version: '8'
          - agp_version: '4.2.0'
            gradle_version: '6.7.1'
            java_version: '8'
          - agp_version: '4.2.0'
            gradle_version: '7.0.2'
            java_version: '8'
          - agp_version: '7.0.0'
            gradle_version: '7.0.2'
            java_version: '11'
          - agp_version: '7.1.0'
            gradle_version: '7.2'
            java_version: '11'
          - agp_version: '7.2.0'
            gradle_version: '7.3.3'
            java_version: '11'
          - agp_version: '7.3.0'
            gradle_version: '7.4.2'
            java_version: '11'
          - agp_version: '7.4.0-rc02'
            gradle_version: '7.5'
            java_version: '11'
          - agp_version: '8.0.0-alpha10'
            gradle_version: '8.0'
            java_version: '17'
            runner_gradle_version: '7.3'

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-java
        with:
          java-version: ${{ matrix.java_version }}
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.runner_gradle_version || '5.4' }}
      - run: gradle testPluginAcceptanceTest
        env:
          TEST_AGP_VERSION: ${{ matrix.agp_version }}
          TEST_GRADLE_VERSION: ${{ matrix.gradle_version }}
          TEST_SERVER_URL: http://localhost:${{ job.services.app.ports[3000] }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports-${{ matrix.agp_version }}-with-${{ matrix.gradle_version }}
          path: build/reports/tests/testPluginAcceptanceTest
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results-${{ matrix.agp_version }}-with-${{ matrix.gradle_version }}
          path: build/test-results/tests/testPluginAcceptanceTest
