name: Release artifacts

on:
  push:
    tags:
      - \d.\d.\d
      - \d.\d.\d-(alpha|rc)\d\d

jobs:
  production-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/checkout@v3
      - run: |
          if [[ "$(cat src/main/resources/VERSION)" != "${GITHUB_REF#refs/tags/}" ]]; then
            echo "version must keep the consistency" 1>&2
            exit 1
          fi
      - uses: ./.github/actions/setup-java
      - name: Set up gradle.properties for signing and nexus
        # Add timeout setting due to https://github.com/DeployGate/gradle-deploygate-plugin/runs/2523846388
        run: |
          echo >> gradle.properties
          cat<<EOF >> gradle.properties
          systemProp.org.gradle.internal.http.socketTimeout=120000
          nexusUsername=${{ secrets.SHARED_NEXUS_USERNAME }}
          nexusPassword=${{ secrets.SHARED_NEXUS_PASSWORD }}
          EOF
      - name: Publish artifacts
        run: ./release.sh
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Gradle Plugin Release'
          SLACK_MESSAGE: "${{ github.ref }} has been published to Sonatype. ref: https://oss.sonatype.org/"
          SLACK_WEBHOOK: ${{ secrets.SHARED_FOR_RELEASE_ARTIFACT_SLACK_INCOMING_WEBHOOK_URL }}
